### ISSUE TITLE
Compatibility with Seurat and SingleCellExperiment objects

### ISSUE THREAD

**Issue by katsikora** [csglab/PhantomPurgeR#1]
Hi,

is there a way to apply `purge_phantoms` on a Seurat or SingleCellExperiment class object?
Converting from these to `.h5` in R is a bit of a headache.
Or would you have another way to make it work with native STARsolo output?

Best,

Katarzyna

**Comment by rfarouni** [comment]
Hi Katarzyna,

The UMI x Cell count matrix output can be converted into a Seurat of SCE object as this example [example](https://csglab.github.io/PhantomPurgeR/assets/notebooks/downstream_analysis_umap.html) shows but you cannot start with these objects because the method needs to combine into one table the read counts -not the UMI counts -for all samples run on the same lane. As for now, only the output of Cellranger can be loaded by the software. That said, you don't necessarily need to convert the files to .h5 format if you can instead  manage to read the data into R and make sure it has the same structure as in the first step of the workflow `out <- read10xMolInfoSamples(samples_filepaths)`. Then you can just skip the first step and  run the rest of the workflow from there.

Rick,

**Comment by katsikora** [comment]
Hi Rick,

I see, thanks for the clarification!

Best,

Katarzyna
